on:
  workflow_dispatch:
  push:
    tags: ['*']

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Build py file
        run: |
          pip install -r requirements-dev.txt
          python -m build
      - name: Move whl to release directory
        run: mkdir to-release && mv dist/certbot_dns_lexicon-*.whl to-release/
      - name: Create release draft
        uses: MaciejSzczurek/release-action@main
        with:
          assets-directory: to-release
